#ifndef DATAHANDLING_GLOBAL_H
#define DATAHANDLING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATAHANDLING_LIBRARY)
#  define DATAHANDLINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATAHANDLINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATAHANDLING_GLOBAL_H
